#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public static class DarkWorldEditor
{
    const string Root="Assets/Mapas/Dark World", Masks=Root+"/Mascaras", Art=Root+"/Arte/DarkWorld.png", Guide=Root+"/Arte/DarkWorld_GabaritoTerritorios.png";
    const string ScenePath=Root+"/DarkWorld.unity", DefinitionPath="Assets/Resources/Mapas/DarkWorld.asset", CatalogPath="Assets/Resources/Mapas/CatalogoMapas.asset", BaseScene="Assets/WarGame.unity";
    const float Ppu=100f, Width=1529f, Height=1019f;
    readonly struct TCfg { public TCfg(string id,string name,string region,float x,float y,float tx,float ty){Id=id;Name=name;Region=region;Position=new Vector2((x-Width/2)/Ppu,(Height/2-y)/Ppu);Counter=new Vector2((tx-x)/Ppu,(y-ty)/Ppu);} public readonly string Id,Name,Region;public readonly Vector2 Position,Counter; }
    static TCfg T(string i,string n,string r,float x,float y,float tx,float ty)=>new TCfg(i,n,r,x,y,tx,ty);
    static readonly TCfg[] Territories={
      T("Lai","Lai","agla",1029,177.5f,1027.3f,177.1f),T("Hevll","Hevll","agla",924,191.5f,922.7f,186.4f),T("SodherNoor","Sodher Noor","flathia",259.5f,202.5f,271.6f,194.9f),T("ValeriaHeart","Valeria Heart","agla",1123,204.5f,1122.7f,201.5f),
      T("SpearOfTheGods","Spear of the gods","flathia",441.5f,224.5f,426.6f,216.4f),T("Talisporto","Talisporto","agla",1009,236.5f,1011.2f,238),T("WhiteWall","White Wall","vorlia",703,283,730.1f,280.8f),T("Marcias","Marcias","akani",1267.5f,294,1279.2f,299),
      T("FlathiaIsland","Flathia Island","flathia",144,321,143.7f,321.6f),T("Cube","Cube","flathia",276.5f,348,270.8f,352.3f),T("CrowsHome","Crows Home","flathia",420,372,416.6f,364.8f),T("Babushka","Babushka","vorlia",805.5f,374,805.5f,375.7f),
      T("FantasyRoom","Fantasy Room","vorlia",669.5f,378,663.8f,384.7f),T("Nai","Nai","akani",1134.5f,396,1141.4f,393.1f),T("PeachLand","Peach Land","akani",1341.5f,424.5f,1340,416.9f),T("Tigershitman","Tigershitman","vorlia",902.5f,412.5f,905.6f,423.9f),
      T("PalmTowner","Palm Towner","flathia",260.5f,491,257,488.1f),T("NewSahara","New Sahara","flathia",365.5f,503,363.8f,504.8f),T("PutfireDistrict","Putfire District","akani",1254,549.5f,1261,545),T("Widows","Widows","birfani",607.5f,563.5f,610,557.6f),
      T("Sheppard","Sheppard","akani",1402.5f,574.5f,1396.6f,559.5f),T("RebeccaIsland","Rebecca Island","akani",1128.5f,564,1128,564.9f),T("Mariliand","Mariliand","birfani",747,570,741.4f,575.6f),T("BadenBaden","Baden Baden","birfani",924.5f,579,913.7f,577.6f),
      T("ValBay","Val Bay","flathia",270,617,267.3f,612),T("Potros","Potros","makatanga_islands",1035.5f,675,1031.2f,670.9f),T("Braveland","Braveland","flathia",337.5f,672.5f,337.6f,674.4f),T("TALand","T A Land","birfani",753.5f,693,767.9f,682.4f),
      T("Maki","Maki","makatanga_islands",1272.5f,713.5f,1261.1f,703.8f),T("MillaSunderland","Milla Sunderland","birfani",873,722,875.6f,717.2f),T("Putfire","Putfire","flathia",446.5f,725,440.5f,730.1f),T("CentralBase","Central Base","makatanga_islands",1095.5f,737,1096.5f,736.6f),
      T("Montreux","Montreux","flathia",299,738,305.5f,737.9f),T("DarknessRoom","Darkness Room","south_pole",655,807,650.3f,807.7f),T("Haeox","Haeox","makatanga_islands",997,806.5f,998,811.7f),T("Lineker","Lineker","makatanga_islands",1165.5f,820,1163.3f,817.6f),
      T("ColdCoast","Cold Coast","south_pole",803.5f,953,810.7f,956.4f),T("Trinit","Trinit","south_pole",940,956.5f,941.7f,959.3f),T("Garin","Garin","south_pole",418.5f,958,423.4f,962.5f),T("Tarantula","Tarantula","south_pole",678.5f,966,677,972),
      T("Demetrius","Demetrius","south_pole",541.5f,966.5f,546.6f,974.1f),T("OffRoad","Off Road","south_pole",1074.5f,969,1070.9f,974.7f),T("KsIsland","Ks Island","south_pole",1182,979,1189.3f,982.8f)};
    static readonly Dictionary<string,(string n,int b,int o,Color c)> Regions=new(StringComparer.Ordinal){["flathia"]=("Flathia",5,0,new Color(.4f,.8f,.3f)),["agla"]=("Agla",3,1,new Color(.3f,.7f,1f)),["vorlia"]=("Vorlia",2,2,new Color(.8f,.35f,.35f)),["akani"]=("Akani",3,3,new Color(.75f,.55f,.25f)),["birfani"]=("Birfani",3,4,new Color(.65f,.4f,.85f)),["makatanga_islands"]=("Makatanga Islands",2,5,new Color(.25f,.8f,.7f)),["south_pole"]=("South Pole",4,6,Color.white)};
    static readonly string[] Land="1-2 1-6 1-4 2-6 3-5 3-10 4-6 5-11 5-10 7-12 7-13 8-15 8-14 10-11 10-17 10-18 11-18 12-16 12-13 14-15 14-19 15-19 15-21 17-18 17-25 18-25 19-21 20-23 20-28 23-28 23-24 24-30 24-28 25-27 25-33 27-33 27-31 28-30 31-33 37-38 37-40 38-42 39-41 40-41 42-43".Split(' ');
    static readonly string[] Special="9-3 22-19 26-30 29-21 32-26 35-32 36-29 34-40 5-7 16-14 18-20 24-22 34-28".Split(' ');

    [MenuItem("War Dominion/Configuração de Mapas/Gerar ou Atualizar/Dark World")]
    public static void Generate(){ValidateSources();AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);ConfigureImports();var map=GenerateDefinition();UpdateCatalog(map);GenerateScene(map);AssetDatabase.SaveAssets();AssetDatabase.Refresh();Validate();Debug.Log($"[Mapa] Dark World gerado: 43 territórios, 7 regiões, {Connections().Count} conexões.");}
    [MenuItem("War Dominion/Configuração de Mapas/Validar/Dark World")]
    public static void Validate(){var map=AssetDatabase.LoadAssetAtPath<DefinicaoMapa>(DefinitionPath);if(map==null)throw new InvalidOperationException("DarkWorld.asset ausente.");var issues=ValidadorDefinicaoMapa.Validar(map);if(issues.Count>0)throw new InvalidOperationException(string.Join(" | ",issues));if(map.Territorios.Count!=43||map.Regioes.Count!=7)throw new InvalidOperationException("Dark World deve possuir 43 territórios e 7 regiões.");ValidateScene();Debug.Log($"[Mapa] Dark World validado: 43/7/{map.Conexoes.Count}.");}
    static List<(string a,string b)> Connections(){return Land.Concat(Special).Select(s=>{var p=s.Split('-').Select(int.Parse).ToArray();return Pair(Territories[p[0]-1].Id,Territories[p[1]-1].Id);}).Distinct().ToList();}
    static (string a,string b) Pair(string a,string b)=>string.CompareOrdinal(a,b)<=0?(a,b):(b,a);
    static DefinicaoMapa GenerateDefinition(){var ts=Territories.Select(t=>new DefinicaoTerritorioMapa{id=t.Id,nomeExibido=t.Name,chaveTraducao="territory_"+t.Id.ToLowerInvariant(),regiaoId=t.Region,posicaoContador=t.Counter,possuiPosicaoContador=true}).ToList();var rs=Regions.Select(r=>new DefinicaoRegiaoMapa{id=r.Key,nomeExibido=r.Value.n,descricao=r.Value.n,chaveTraducao="region_"+r.Key,bonus=r.Value.b,ordemExibicao=r.Value.o,corDestaque=r.Value.c,territorioIds=Territories.Where(t=>t.Region==r.Key).Select(t=>t.Id).ToList()}).OrderBy(r=>r.ordemExibicao).ToList();var cs=Connections().Select(p=>new DefinicaoConexaoMapa{origemId=p.a,destinoId=p.b,tipo=TipoConexaoMapa.Terrestre,bidirecional=true}).ToList();var m=AssetDatabase.LoadAssetAtPath<DefinicaoMapa>(DefinitionPath);if(m==null){m=ScriptableObject.CreateInstance<DefinicaoMapa>();AssetDatabase.CreateAsset(m,DefinitionPath);}m.ConfigurarNoEditor("dark_world","DarkWorld","Dark World","Dark World com 43 territórios e sete regiões.","dark_world",AssetDatabase.LoadAssetAtPath<Sprite>(Art),Vector2.zero,5.2f,ts,rs,cs);EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);return m;}
    static void UpdateCatalog(DefinicaoMapa map){var c=AssetDatabase.LoadAssetAtPath<CatalogoMapas>(CatalogPath);if(c==null||c.MapaPadrao==null)throw new InvalidOperationException("Catálogo ausente.");var maps=c.Mapas.Where(x=>x!=null&&x.MapaId!="dark_world").Distinct().ToList();maps.Add(map);c.ConfigurarNoEditor(c.MapaPadrao,maps);EditorUtility.SetDirty(c);AssetDatabase.SaveAssetIfDirty(c);}
    static void ConfigureImports(){Configure(Art,2048);foreach(var t in Territories)Configure(Masks+"/"+t.Id+".png",1024);}
    static void Configure(string path,int max){var i=AssetImporter.GetAtPath(path) as TextureImporter;if(i==null)throw new InvalidOperationException("Importer ausente: "+path);i.textureType=TextureImporterType.Sprite;i.spriteImportMode=SpriteImportMode.Single;i.spritePixelsPerUnit=Ppu;i.alphaSource=TextureImporterAlphaSource.FromInput;i.alphaIsTransparency=true;i.mipmapEnabled=false;i.npotScale=TextureImporterNPOTScale.None;i.textureCompression=TextureImporterCompression.Uncompressed;i.maxTextureSize=max;i.filterMode=FilterMode.Bilinear;i.SaveAndReimport();}
    static void GenerateScene(DefinicaoMapa map){if(AssetDatabase.LoadAssetAtPath<SceneAsset>(ScenePath)!=null&&!AssetDatabase.DeleteAsset(ScenePath))throw new InvalidOperationException("Falha ao substituir cena.");if(!AssetDatabase.CopyAsset(BaseScene,ScenePath))throw new InvalidOperationException("Falha ao copiar cena base.");var scene=EditorSceneManager.OpenScene(ScenePath,OpenSceneMode.Single);var parent=GameObject.Find("Territorios");var model=parent?.transform.Find("Arabia");if(model==null)throw new InvalidOperationException("Molde ausente.");parent.transform.SetLocalPositionAndRotation(Vector3.zero,Quaternion.identity);parent.transform.localScale=Vector3.one;var news=new List<GameObject>();for(int n=0;n<43;n++){var o=UnityEngine.Object.Instantiate(model.gameObject,parent.transform,false);o.name="__DarkWorld_"+n;news.Add(o);}for(int n=parent.transform.childCount-1;n>=0;n--)if(!parent.transform.GetChild(n).name.StartsWith("__DarkWorld_",StringComparison.Ordinal))UnityEngine.Object.DestroyImmediate(parent.transform.GetChild(n).gameObject);for(int n=0;n<43;n++)Setup(news[n],Territories[n]);var visual=GameObject.Find("classic_0");visual.name="DarkWorld_Arte";visual.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);visual.transform.localScale=Vector3.one;var vr=visual.GetComponent<SpriteRenderer>();vr.sprite=map.ArteBase;vr.color=Color.white;vr.sortingOrder=2;if(Camera.main!=null){Camera.main.transform.position=new Vector3(0,0,Camera.main.transform.position.z);Camera.main.orthographicSize=5.2f;}EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene,ScenePath);}
    static void Setup(GameObject o,TCfg t){o.name=t.Id;o.transform.SetLocalPositionAndRotation(new Vector3(t.Position.x,t.Position.y,0),Quaternion.identity);o.transform.localScale=Vector3.one;var s=AssetDatabase.LoadAssetAtPath<Sprite>(Masks+"/"+t.Id+".png");var r=o.GetComponent<SpriteRenderer>();r.sprite=s;r.color=Color.white;r.sortingOrder=0;var click=o.GetComponent<TerritorioClique>();click.idTerritorio=t.Id;click.chaveTraducao="territory_"+t.Id.ToLowerInvariant();click.continente=(TerritorioClique.Continente)Mathf.Clamp(Regions[t.Region].o,0,5);click.dono=TerritorioClique.Dono.Neutro;(o.GetComponent<TerritorioTropas>()??o.AddComponent<TerritorioTropas>()).Quantidade=1;o.GetComponent<TerritorioFronteiras>().Configurar(Array.Empty<TerritorioClique>());var old=o.GetComponent<PolygonCollider2D>();if(old!=null)UnityEngine.Object.DestroyImmediate(old);var col=o.AddComponent<PolygonCollider2D>();col.pathCount=s.GetPhysicsShapeCount();var pts=new List<Vector2>();for(int n=0;n<col.pathCount;n++){pts.Clear();s.GetPhysicsShape(n,pts);col.SetPath(n,pts);}var counter=o.transform.Find("ContadorModerno");counter.localPosition=new Vector3(t.Counter.x,t.Counter.y,0);}
    static void ValidateSources(){if(Dim(Art)!=new Vector2Int(1529,1019)||Dim(Guide)!=new Vector2Int(1529,1019))throw new InvalidOperationException("Arte/gabarito Dark World não estão 1:1 em 1529x1019.");if(Territories.Length!=43||Regions.Count!=7)throw new InvalidOperationException("Configuração 43/7 inválida.");foreach(var t in Territories)if(!File.Exists(Path.GetFullPath(Masks+"/"+t.Id+".png")))throw new FileNotFoundException(t.Id);}
    static Vector2Int Dim(string p){var t=new Texture2D(2,2);try{ImageConversion.LoadImage(t,File.ReadAllBytes(Path.GetFullPath(p)));return new Vector2Int(t.width,t.height);}finally{UnityEngine.Object.DestroyImmediate(t);}}
    static void ValidateScene(){var previous=SceneManager.GetActiveScene();bool open=previous.path==ScenePath;var scene=open?previous:EditorSceneManager.OpenScene(ScenePath,OpenSceneMode.Additive);try{var all=scene.GetRootGameObjects().SelectMany(x=>x.GetComponentsInChildren<TerritorioClique>(true)).ToArray();if(all.Length!=43||all.Select(x=>x.idTerritorio).Distinct().Count()!=43)throw new InvalidOperationException("Cena sem 43 IDs únicos.");foreach(var t in all){var c=t.GetComponent<PolygonCollider2D>();var n=t.transform.Find("ContadorModerno");if(c==null||c.pathCount==0||n==null||!c.OverlapPoint(n.position))throw new InvalidOperationException("Geometria/contador inválido: "+t.idTerritorio);}}finally{if(!open)EditorSceneManager.CloseScene(scene,true);}}
}
#endif
